//! Resource trait system — the core abstraction for GW2 API endpoints.
//!
//! | Trait                           | Endpoint shape                              |
//! |---------------------------------|---------------------------------------------|
//! | [`Resource`]                    | `GET /v2/items/{id}` — bulk, ID-addressed   |
//! | [`PagedResource`]               | `Resource` + `?page=N` pagination           |
//! | [`SingletonResource`]           | `GET /v2/account` — fixed URL, one object   |
//! | [`CollectionSingletonResource`] | `GET /v2/account/bank` — fixed URL, `Vec`   |
//!
//! Typed IDs (`ItemId`, `RecipeId`, …) are generated by `#[gw2_endpoint(id_type = u32)]`.
//! Each ID newtype:
//! - Deserializes from a plain integer/string **or** an `{"id": N}` JSON object
//! - Serializes as a plain integer/string
//! - Has a `.get(&client)` method to fetch the associated resource

use std::fmt;
use std::hash::Hash;

use serde::de::DeserializeOwned;

pub use ops::PageOptions;

mod ops;

// ── ID trait ────────────────────────────────────────────────────────────────

/// Trait implemented by all typed ID newtypes.
///
/// GW2 API IDs come in three flavours:
/// - `u32` — most entity IDs (items, recipes, skills, colors, …)
/// - UUID `String` — achievement groups, accounts, guilds
/// - Plain `String` — some world/locale-keyed endpoints
///
/// All three satisfy this trait. `Clone` is required rather than `Copy` because
/// `String` is not `Copy`.
pub trait ResourceId:
    fmt::Display + DeserializeOwned + Clone + Eq + Hash + Send + Sync + 'static
{
}

impl ResourceId for u32 {}
impl ResourceId for u64 {}
impl ResourceId for String {}

// ── Multi-resource trait ────────────────────────────────────────────────────

/// A GW2 API resource that lives at `/{PATH}/{id}` and supports bulk access.
///
/// Implemented via `#[gw2_endpoint(path = "...", id_type = u32)]`, which gives the type
/// access to all generic client operations:
/// [`get`][crate::client::Gw2Client::get], [`get_many`][crate::client::Gw2Client::get_many],
/// [`list_ids`][crate::client::Gw2Client::list_ids], and [`all`][crate::client::Gw2Client::all].
pub trait Resource: DeserializeOwned + Send + Sync + 'static {
    /// The typed ID for this resource.
    type Id: ResourceId;

    /// The base URL path, without leading slash. E.g. `"items"` or `"commerce/prices"`.
    const PATH: &'static str;
}

/// Marker trait: this resource supports `?page=N&page_size=M` pagination.
///
/// Opt in via `#[gw2_endpoint(paged, ...)]`. Enables
/// [`pages`][crate::client::Gw2Client::pages] and
/// [`all`][crate::client::Gw2Client::all] on the client.
pub trait PagedResource: Resource {}

// ── Patch trait ─────────────────────────────────────────────────────────────

/// A resource that may require client-side corrections for known API bugs.
///
/// The GW2 API has a small number of well-documented permanent bugs where the
/// API returns incorrect data — for example, some miniatures always return
/// `name: "((208738))"` and `item_id: 6` instead of their actual name and
/// unlock item. The correct data is available from other endpoints.
///
/// Types that have known-bad entries override `patch` to apply corrections.
/// The default implementation is a no-op, so all well-behaved resources
/// compile to zero overhead.
///
/// This trait is automatically implemented (as a no-op) by `#[gw2_endpoint]`.
/// Override it in a separate `impl` block to apply corrections:
///
/// ```rust,ignore
/// impl Patchable for Mini {
///     fn patch(&mut self) {
///         // apply corrections from a lookup table
///     }
/// }
/// ```
///
/// `patch` is called automatically by [`get`][crate::client::Gw2Client::get]
/// and [`get_many`][crate::client::Gw2Client::get_many] after deserialization.
pub trait Patchable: Resource {
    /// Apply any known corrections to this resource value.
    ///
    /// The default implementation is a no-op.
    fn patch(&mut self) {}
}

// ── Singleton resource trait ────────────────────────────────────────────────

/// A GW2 API singleton resource — lives at a fixed URL with no ID segment.
///
/// Examples:
/// - `/v2/account` (auth required)
/// - `/v2/tokeninfo` (auth required)
/// - `/v2/build` (public)
///
/// Implemented via `#[gw2_endpoint(path = "...", auth)]`, which generates a typed accessor on
/// [`Gw2Client`][crate::client::Gw2Client].
pub trait SingletonResource: DeserializeOwned + Send + Sync + 'static {
    /// The URL path, without leading slash. E.g. `"account"` or `"tokeninfo"`.
    const PATH: &'static str;
}

// ── Collection singleton resource trait ─────────────────────────────────────

/// A GW2 API endpoint that lives at a fixed URL and returns a **list** of items.
///
/// This covers account sub-resources that return `Vec<T>` rather than a single
/// object — for example:
/// - `GET /v2/account/wallet` → `Vec<WalletEntry>`
/// - `GET /v2/account/bank` → `Vec<Option<BankSlot>>`
/// - `GET /v2/account/materials` → `Vec<MaterialEntry>`
///
/// The `Item` associated type is the element type of the returned `Vec`.
/// `Vec<Self::Item>` must itself be `DeserializeOwned`.
///
/// Implemented via `#[gw2_endpoint(path = "...", collection, auth)]`, which generates a
/// typed accessor on [`Gw2Client`][crate::client::Gw2Client] that returns
/// `Result<Vec<Self::Item>, Gw2ApiError>`.
pub trait CollectionSingletonResource: Send + Sync + 'static {
    /// The element type returned in the collection.
    type Item: DeserializeOwned + Send + Sync + 'static;

    /// The URL path, without leading slash. E.g. `"account/wallet"`.
    const PATH: &'static str;
}
