//! Generic client operations over [`Resource`], [`SingletonResource`], and [`CollectionSingletonResource`].
//!
//! | Operation                  | Method                                  | Endpoint shape              |
//! |----------------------------|-----------------------------------------|-----------------------------|
//! | Fetch singleton            | `client.fetch_singleton::<TokenInfo>()` | Fixed URL, one object       |
//! | Fetch collection singleton | `client.fetch_collection::<Bank>()`     | Fixed URL, `Vec`            |
//! | Fetch by ID                | `client.get::<Item>(id)`                | `/{path}/{id}`              |
//! | Fetch many by ID           | `client.get_many::<Item>(ids)`          | `/{path}?ids=1,2,3`         |
//! | List all IDs               | `client.list_ids::<Item>()`             | `/{path}` (no args)         |
//! | Fetch all                  | `client.all::<Item>()`                  | `?ids=all` or all pages     |
//! | Stream pages               | `client.pages::<Item>(opts)`            | `?page=N&page_size=M`       |

use async_stream::stream;
use futures::{Stream, TryStreamExt};

use crate::client::Gw2Client;
use crate::client::auth::AuthState;
use crate::error::Gw2ApiError;

use super::{CollectionSingletonResource, PagedResource, Patchable, Resource, SingletonResource};

/// Options for paginated streaming.
#[derive(Debug, Clone)]
pub struct PageOptions {
    /// The page number to start from (0-indexed). Default: 0.
    pub start_page: u32,
    /// Stop after this page number (exclusive). `None` streams until exhausted.
    pub end_page: Option<u32>,
    /// Items per page (1–200). Default: 50.
    pub page_size: u32,
}

impl Default for PageOptions {
    fn default() -> Self {
        Self {
            start_page: 0,
            end_page: None,
            page_size: 50,
        }
    }
}

impl PageOptions {
    /// Set the page size (clamped to 1–200).
    pub fn page_size(mut self, size: u32) -> Self {
        self.page_size = size.clamp(1, 200);
        self
    }

    /// Stream only pages in `start..end`.
    pub fn range(mut self, start: u32, end: u32) -> Self {
        self.start_page = start;
        self.end_page = Some(end);
        self
    }
}

// ── Singleton operations ────────────────────────────────────────────────────

impl<S: AuthState> Gw2Client<S> {
    /// Fetch a singleton resource (no ID required).
    ///
    /// For auth-only singletons, prefer the typed accessor generated by
    /// `#[gw2_endpoint(path = "...", auth)]`, which restricts the call to
    /// `Gw2Client<Authenticated>`.
    pub(crate) async fn fetch_singleton<R: SingletonResource>(&self) -> Result<R, Gw2ApiError> {
        self.request(format!("/{}", R::PATH)).send().await
    }
}

impl<S: AuthState> Gw2Client<S> {
    /// Fetch a collection singleton resource (fixed URL, returns `Vec<Item>`).
    ///
    /// Used for account sub-resources like `/v2/account/wallet`, `/v2/account/bank`, etc.
    /// These live at a fixed URL (no ID), but return a list rather than a single object.
    pub(crate) async fn fetch_collection<R: CollectionSingletonResource>(
        &self,
    ) -> Result<Vec<R::Item>, Gw2ApiError> {
        self.request(format!("/{}", R::PATH)).send().await
    }
}

// ── Multi-resource operations ───────────────────────────────────────────────

impl<S: AuthState> Gw2Client<S> {
    /// Fetch a single resource by ID.
    ///
    /// Results are cached transparently. Subsequent calls with the same ID and type
    /// return the cached value without an API request.
    ///
    /// Known API bugs are corrected automatically via [`Patchable::patch`].
    pub(crate) async fn get<R: Resource + Patchable>(
        &self,
        id: impl Into<R::Id>,
    ) -> Result<R, Gw2ApiError> {
        // Accepts raw u32 or typed newtype (e.g. ItemId) interchangeably.
        // Typed newtypes don't catch wrong-value mistakes (ItemId(999) is just as wrong
        // as 999), so requiring the wrapper buys no safety — only boilerplate.
        // Shim pattern: converts here and delegates so the heavy body in get_by_id
        // monomorphizes once per R, not once per (R × Into implementor).
        self.get_by_id(id.into()).await
    }

    async fn get_by_id<R: Resource + Patchable>(&self, id: R::Id) -> Result<R, Gw2ApiError> {
        // Cache read
        if let Some(cached) = self.inner.cache.get::<R>(&id).await {
            return Ok(cached);
        }

        // Fetch from API as raw JSON so we can cache it before deserializing
        let path = format!("/{}/{}", R::PATH, id);
        let raw: serde_json::Value = self.request(path).send().await?;

        // Cache write (raw JSON — corrections are applied after deserialization)
        self.inner.cache.insert::<R>(&id, raw.clone()).await;

        let mut value: R = serde_json::from_value(raw).map_err(Gw2ApiError::Json)?;
        value.patch();
        Ok(value)
    }

    /// Fetch multiple resources by IDs (auto-chunked at 200 per request).
    ///
    /// Returns an empty `Vec` for empty input.
    ///
    /// Known API bugs are corrected automatically via [`Patchable::patch`].
    pub(crate) async fn get_many<R: Resource + Patchable>(
        &self,
        ids: impl IntoIterator<Item = R::Id>,
    ) -> Result<Vec<R>, Gw2ApiError> {
        let ids: Vec<R::Id> = ids.into_iter().collect();
        if ids.is_empty() {
            return Ok(Vec::new());
        }

        const CHUNK_SIZE: usize = 200;
        let mut results = Vec::with_capacity(ids.len());

        for chunk in ids.chunks(CHUNK_SIZE) {
            let mut chunk_results: Vec<R> = self
                .request(format!("/{}", R::PATH))
                .ids(chunk.iter())
                .send()
                .await?;
            for item in &mut chunk_results {
                item.patch();
            }
            results.extend(chunk_results);
        }

        Ok(results)
    }

    /// List all IDs for a resource type.
    ///
    /// Equivalent to Python's `await Item.all(expanded=False)`.
    pub(crate) async fn list_ids<R: Resource>(&self) -> Result<Vec<R::Id>, Gw2ApiError> {
        self.request(format!("/{}", R::PATH)).send().await
    }

    /// Fetch all resources of this type.
    ///
    /// Tries `?ids=all` first; on [`Gw2ApiError::BadRequest`] (endpoint doesn't support it),
    /// falls back to full pagination. Equivalent to Python's `await Item.all(expanded=True)`.
    pub(crate) async fn all<R: Resource + PagedResource>(&self) -> Result<Vec<R>, Gw2ApiError> {
        match self
            .request(format!("/{}", R::PATH))
            .param("ids", "all")
            .send::<Vec<R>>()
            .await
        {
            Ok(results) => Ok(results),
            Err(Gw2ApiError::BadRequest(_)) => {
                // Endpoint doesn't support ids=all — collect all pages
                self.pages::<R>(PageOptions::default().page_size(200))
                    .try_collect()
                    .await
            }
            Err(e) => Err(e),
        }
    }

    /// Stream all resources page by page.
    ///
    /// Equivalent to Python's `async for item in Item.pages(...)`.
    ///
    /// Uses the `X-Page-Total` response header to determine when to stop automatically.
    /// You can also set an explicit end page via [`PageOptions::range`].
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// use futures::StreamExt;
    ///
    /// let mut stream = client.pages::<Item>(PageOptions::default().page_size(200));
    /// while let Some(item) = stream.next().await {
    ///     let item = item?;
    ///     println!("{}", item.name);
    /// }
    /// ```
    pub(crate) fn pages<R: PagedResource>(
        &self,
        opts: PageOptions,
    ) -> impl Stream<Item = Result<R, Gw2ApiError>> + '_ {
        stream! {
            if let Err(e) = validate_page_opts(&opts) {
                yield Err(e);
                return;
            }

            let mut page = opts.start_page;
            let total_pages: Option<u32> = opts.end_page;

            loop {
                if let Some(end) = total_pages {
                    if page >= end {
                        break;
                    }
                }

                let result: Result<Vec<R>, Gw2ApiError> = self
                    .request(format!("/{}", R::PATH))
                    .page(page, opts.page_size)
                    .send()
                    .await;

                match result {
                    Ok(items) => {
                        let count = items.len() as u32;
                        for item in items {
                            yield Ok(item);
                        }
                        // Stop if we got fewer items than requested (last page)
                        if count < opts.page_size {
                            break;
                        }
                        page += 1;
                    }
                    Err(Gw2ApiError::BadRequest(_)) | Err(Gw2ApiError::NotFound(_)) => {
                        // Exhausted pages
                        break;
                    }
                    Err(e) => {
                        yield Err(e);
                        break;
                    }
                }
            }
        }
    }
}

fn validate_page_opts(opts: &PageOptions) -> Result<(), Gw2ApiError> {
    if opts.page_size == 0 || opts.page_size > 200 {
        return Err(Gw2ApiError::InvalidPagination(
            "page_size must be between 1 and 200".into(),
        ));
    }
    Ok(())
}
