/**
 * Helpers around the generated IPC bindings.
 *
 * The commands and their types live in `bindings.ts`, generated by
 * tauri-specta from `src-tauri` on every debug start (or
 * `cargo run -p gw2-companion-app --features bindgen --bin export-bindings`).
 * Never hand-write a mirror of a Rust type here.
 */
import type { Result } from './bindings';

/** Unwrap a command's `Result`, throwing its error string. */
export async function unwrap<T>(res: Promise<Result<T, string>>): Promise<T> {
	const r = await res;
	if (r.status === 'error') throw new Error(r.error);
	return r.data;
}

/** Format copper value as gold/silver/copper string. */
export function formatCoin(copper: number): string {
	const abs = Math.abs(copper);
	const g = Math.floor(abs / 10000);
	const s = Math.floor((abs % 10000) / 100);
	const c = abs % 100;
	const sign = copper < 0 ? '-' : '';

	if (g > 0) return `${sign}${g}g ${String(s).padStart(2, '0')}s ${String(c).padStart(2, '0')}c`;
	if (s > 0) return `${sign}${s}s ${String(c).padStart(2, '0')}c`;
	return `${sign}${c}c`;
}
