
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Get account info (requires API key).
 */
async getAccountInfo() : Promise<Result<AccountView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single item by ID.
 */
async getItem(id: number) : Promise<Result<ItemView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_item", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get multiple items by ID.
 */
async getItems(ids: number[]) : Promise<Result<ItemView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_items", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get trading post price for an item.
 */
async getItemPrice(id: number) : Promise<Result<ItemPriceView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_item_price", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search recipes that produce a given item.
 */
async searchRecipesByOutput(itemId: number) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_recipes_by_output", { itemId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set (or update) the API key. Persists to DB.
 */
async setApiKey(key: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if an API key is configured.
 */
async getApiKeyStatus() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_api_key_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsGet() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whole-snapshot save — the frontend merges its patch and sends everything.
 */
async settingsSave(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_save", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * `/v2/account`, as the dashboard shows it.
 */
export type AccountView = { id: string; name: string; world: number; created: string; 
/**
 * Games and expansions the account owns, as API strings.
 */
access: string[]; commander: boolean; 
/**
 * Needs the `progression` scope.
 */
fractal_level: number | null; 
/**
 * Needs the `progression` scope.
 */
daily_ap: number | null; 
/**
 * Needs the `progression` scope.
 */
monthly_ap: number | null; 
/**
 * Needs the `progression` scope.
 */
wvw_rank: number | null; wvw_team_id: number | null }
export type AppSettings = { 
/**
 * Whether first-launch onboarding has been completed or skipped.
 */
onboarding_completed: boolean }
/**
 * `/v2/commerce/prices` for one item.
 */
export type ItemPriceView = { id: number; whitelisted: boolean; buys: PriceSide; sells: PriceSide }
/**
 * An item's common fields; the type-specific `details` are not exposed yet.
 */
export type ItemView = { id: number; chat_link: string; name: string; icon: string | null; description: string | null; item_type: string; rarity: string; level: number; 
/**
 * Copper.
 */
vendor_value: number }
/**
 * One side of the trading post for an item.
 */
export type PriceSide = { quantity: number; 
/**
 * Copper.
 */
unit_price: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
