//! Endpoint accessors — each module provides a typed handle
//! for a group of related API endpoints.
//!
//! Most accessors are auto-generated by the `#[gw2_resource]`, `#[gw2_singleton]`,
//! and `#[gw2_collection_singleton]` macros. Namespace handles (e.g. `commerce()`)
//! are defined in their respective endpoint modules.

pub mod account;
pub mod achievements;
pub mod commerce;
pub mod createsubtoken;
pub mod currencies;
pub mod items;
pub mod itemstats;
pub mod minis;
pub mod novelties;
pub mod recipes;
pub mod skills;
pub mod skins;
pub mod tokeninfo;
